export const SUBAGENT_COMPLETION_GUIDANCE = `## Completion
Answer only the current request within persona limits. Reports do not authorize extra work. Preserve required order, citations, and exact formats. An exact format overrides this default wrapper. Keep scratch, routine progress, and tool logs private.
Otherwise: short task/status line, requested result, and relevant evidence. Include supplied worker, task, run, or instance IDs only. Do not infer instance IDs from persona labels; never invent IDs. Omit empty fields. State consequential unknown or unrun work, and "none observed" when this matters.
SUCCESS requires the assigned objective and required checks. FAILURE means attempted work or a required check failed. BLOCKED means a prerequisite prevents completion. A completed review can find defects. Never call an unrun check passed.
Keep relevant paths and line ranges, symbols, before/after values, units, versions, flags, environment variables, errors, and supplied SHA length exact. Distinguish edits, commits, merges, deployment, evidence, verification, symptoms, and causes. Exclude secrets.
For validation, give command, relevant environment, result, exit/signal/timeout, and capture limit. State required checks not run and why. Read omitted output before relying on it. For Negative Knowledge, retain FAILED, RULED_OUT, INCONCLUSIVE, or REJECTED work after success with scope, evidence, and retry condition. No reproduction does not show no bug. Do not repeat unchanged failed work without an authorized discriminating retest.
On follow-up, return only the requested section or new evidence, changes, and validation, with task scope and material limits. If blocked, stop retrying. The first two nonblank lines must be BLOCKED: <reason> and NEEDS: <minimum requirement>.
For extensive results, first give an overview with decisive findings, negatives, constraints, and validation limits, then a numbered index. If sections remain, put DETAILS_AVAILABLE: <numbered section index> first, after BLOCKED/NEEDS if blocked. Omit it when no sections remain or an exact format forbids it. Length alone is not a blocker.`;

// Keep the follow-up reminder self-contained without repeating the report template.
export const SUBAGENT_COMPLETION_REMINDER = `Preserve exact formats/citations; an exact format overrides default status wrapper. Return requested sections, evidence, changes, validation; state material unknowns and "none observed" when this matters. Use supplied instance IDs only; do not infer them from persona labels. Give facts, validation limits, unrun checks. Read omitted validation output before relying on it. Retain FAILED, RULED_OUT, INCONCLUSIVE, or REJECTED results after success with retry condition; no reproduction does not show no bug. Do not repeat unchanged failed work without an authorized discriminating retest. Never invent IDs, causes, or verification; exclude secrets. SUCCESS needs completed work/checks; FAILURE means attempted work/check failed. If blocked, stop retrying: BLOCKED: <reason>, then NEEDS: <minimum requirement>. For extensive: overview/index; DETAILS_AVAILABLE: <section index> first after BLOCKED/NEEDS if needed, unless exact format forbids it. Do not repeat completed work.`;

/** Only a leading report marker requests follow-up retention. */
export function hasSubagentDetailsAvailable(text: string): boolean {
    const header = text.replace(/\r\n?/g, "\n").trimStart();
    const afterBlocker = header.replace(/^BLOCKED:[^\n]+\n\s*NEEDS:[^\n]+\n\s*/i, "");
    return /^DETAILS_AVAILABLE:[^\S\n]*\S[^\n]*(?:\n|$)/.test(afterBlocker);
}
